# Generated by Django 4.2 on 2023-06-20 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_alter_message_message_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
